site_name: GImage
site_description: 'GImage - A PHP library for easy image handling.'
site_author: 'Jose Quintana'
site_url: https://joseluisq.github.io/gimage/

repo_url: https://github.com/joseluisq/gimage/
edit_uri: ""

theme:
    name: 'material'
    palette:
        primary: 'blue-grey'
        accent: 'indigo'
    font:
        text: 'Fira Sans'
        code: 'Droid Sans Mono'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/joseluisq'
    - type: 'twitter'
      link: 'https://twitter.com/joseluis_q'

markdown_extensions:
    - codehilite
    - admonition
    - meta
    - toc(permalink=true)
    - markdown.extensions.tables
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.magiclink:
        repo_url_shortener: true
        repo_url_shorthand: true
        provider: "github"
        user: "facelessuser"
        repo: "pymdown-extensions"
    - pymdownx.tilde
    - pymdownx.emoji
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist(custom_checkbox=true)

nav:
    - 'Introduction': 'index.md'
    - 'Getting Started': 'getting-started.md'
    - 'Classes':
        - 'Image': './classes/image.md'
        - 'Figure': './classes/figure.md'
        - 'Text': './classes/text.md'
        - 'Canvas': './classes/canvas.md'
    - 'Examples':
        - 'Cropping': './examples/cropping.md'
        - 'Swapping formats': './examples/swapping-formats.md'
        - 'Resizing': './examples/resizing.md'
        - 'Rotation': './examples/rotation.md'
        - 'Creating figures': './examples/creating-figures.md'
        - 'Text embedding': './examples/text-embedding.md'
        - 'Composing with canvas': './examples/composing-with-canvas.md'
        - 'Render images in-memory': './examples/render-images-in-memory.md'
        - 'Image resource loading': './examples/image-resource-loading.md'
        - 'Creating a presentation card': './examples/creating-a-presentation-card.md'
    - 'API Documentation': 'api.md'
